# This is the docker-compose file for a Flask application.
services:
  flaskapp:
    container_name: ${FLASKAPP_NAME}
    command: gunicorn -w 4 -b :5000 app:app
    #command: ./run.sh ${FLASKAPP_FILE}
    #command: python ./${FLASKAPP_FILE}
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./flaskapp/:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${FLASKAPP_PORT}:5000
    env_file:
      - ./.env
      #- ./.env_flaskapp
    depends_on:
      redis:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      FLASK_ENV: development  # Added environment variable for Flask environment

  redis:
    image: redis:latest
    container_name: redis_server
    restart: unless-stopped
    command: >
      redis-server
      --save "3600 1"
      --appendonly no
      --dir /data
      --dbfilename dump.rdb
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 30s

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDISINSIGHT_HOST=0.0.0.0
      - REDISINSIGHT_ACCEPT_LICENSE=true
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - default

volumes:
  redis_data:
  redisinsight_data:

networks:
  default:
    name: flaskapps-network
    #external: true # uncomment this on production
    driver: bridge
